apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumerapp-deployment
  namespace: message-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumerapp
  template:
    metadata:
      labels:
        app: consumerapp
    spec:
      containers:
        - name: consumerapp
          image: markbogelund/consumerapp:latest
          env:
            - name: ENVIRONMENT
              value: "deployment"
            - name: DATABASE_CONNECTION_STRING
              value: "Host=postgres-service;Port=5432;Username=postgres;Password=postgres;Database=messagesDB"
            - name: LOCAL_DATABASE_CONNECTION_STRING
              value: "Host=localhost;Port=5432;Database=messagesDB;Username=postgres;Password=postgres"
            - name: RABBITMQ_URI
              value: "amqp://guest:guest@rabbitmq-service:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: consumerapp-service
  namespace: message-management-system
spec:
  selector:
    app: consumerapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
