apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: message-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "messagesDB"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: message-management-system
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
